---
title: "Global input for stand-age and fAPAR"
author: "Yunke Peng"
date: "28 09 2021"
output: html_document
---

## Introduction about Global nc files

Elements below are global inputs that will be used in statistical model-based calculations. All data has a final resolution as 0.5 * 0.5 degree. It was long-term average according to their paper's description.

 * stand age (yrs) (Poulter et al. 2019: https://doi.pangaea.de/10.1594/PANGAEA.889943)
 * fAPAR (3g GIMMS: https://developers.google.com/earth-engine/datasets/catalog/NASA_GIMMS_3GV0)

#1. stand age
```{r}
library(raster)
library(ncdf4)
library(dplyr)
library(maps)
library(rgdal)
devtools::load_all("/Users/yunpeng/yunkepeng/latest_packages/rbeni/") 

#set the path and filename
ncfname <- paste ("~/data/GFAD/data_orig/", "GFAD_V1-1", ".nc", sep="")
#ncfname <- paste ("E:/C-N cycling/Carbon allocation/672 sites analysis/stand age/GFAD2/", "GFAD_V1-1", ".nc", sep="")

#1. open a netCDF file and check variable
ncin <- nc_open(ncfname)

#2. Get coordinate and value
lon <- ncvar_get(ncin,"lon")
nlon <- dim(lon) 
lat<-ncvar_get(ncin,"lat")
nlat<-dim(lat)
age <-ncvar_get(ncin,"age")
nc_close(ncin)

pre.vec.long <- as.vector(age)
pre.mat <- matrix(pre.vec.long, nrow = nlon * nlat, ncol = 4*15) # 259200 columns * 60 rows - here 60 represents 4 PFTs and 15 age classes.

lonlat <- expand.grid(lon, lat)
lonlat$age <- rowSums(pre.mat[,1:4])*5+rowSums(pre.mat[,5:8])*15+rowSums(pre.mat[,9:12])*25+rowSums(pre.mat[,13:16])*35+rowSums(pre.mat[,17:20])*45+rowSums(pre.mat[,21:24])*55+rowSums(pre.mat[,25:28])*65+rowSums(pre.mat[,29:32])*75+rowSums(pre.mat[,33:36])*85+rowSums(pre.mat[,37:40])*95+rowSums(pre.mat[,41:44])*105+rowSums(pre.mat[,45:48])*115+rowSums(pre.mat[,49:52])*125+rowSums(pre.mat[,53:56])*135+rowSums(pre.mat[,57:60])*145
names(lonlat) <- c("lon","lat","age")

age_input <- as.data.frame(lonlat)
summary(age_input)
dim(age_input)

coordinates(age_input) <- ~lon+lat 
gridded(age_input) <- TRUE
r <- raster(age_input, "age") 
plot(r) # now it shows an empty grid in lower AUS, also in some other regions. We need to interpolate them based on local mean value.

#2. Input continent map
ncfname <- paste ("~/data/landmasks/", "srex-region-masks_20120709.srex_mask_SREX_masks_all.05deg.time-invariant", ".nc", sep="")
#ncfname <- paste ("D:/PhD/nimpl_sofun_inputs/Data/srex/", "srex-region-masks_20120709.srex_mask_SREX_masks_all.05deg.time-invariant", ".nc", sep="")
ncin <- nc_open(ncfname)

lon <- ncvar_get(ncin,"lon")
nlon <- dim(lon) 
lat<-ncvar_get(ncin,"lat")
nlat <- dim(lat)
area <- ncvar_get(ncin,"srex_mask")
nc_close(ncin)

area1 <- as.vector(area)

lonlat <- expand.grid(lon, lat)
continent_input <- as.data.frame(cbind(lonlat,area1))
names(continent_input) <- c("lon","lat","area")

#merge continents and age
continent_age <- merge(continent_input, age_input, by=c("lon","lat"), all.x = T, sort=F )
summary(continent_age)

#3. Input fAPAR, and merge it with continent_age, and convert fAPAR's NA grid to those age = NA
ncfname <- paste ("~/data/fAPAR/fAPAR3g_v2/", "fAPAR3g_v2_1982_2016_FILLED", ".nc", sep="")
#ncfname <- paste ("D:/PhD/nimpl_sofun_inputs/Data/fAPAR/", "fAPAR3g_v2_1982_2016_FILLED", ".nc", sep="")
dname <- "FAPAR_FILLED"

ncin <- nc_open(ncfname)

lon <- ncvar_get(ncin,"LON")
nlon <- dim(lon) 

lat<-ncvar_get(ncin,"LAT")
nlat <- dim(lat)

FAPAR <- ncvar_get(ncin,"FAPAR_FILLED")
nc_close(ncin)

pre.vec.long <- as.vector(FAPAR)

pre.mat <- matrix(pre.vec.long, nrow = nlon * nlat, ncol = 420) # 259200 * 420 (420 is 35 years: 1982-2016)

fAPAR1982_2011 <- pre.mat[,c(1:360)] #extrat fAPAR from 1982-2011

final_fAPAR <- rowMeans(fAPAR1982_2011,na.rm = TRUE) # calculate means

lonlat <- expand.grid(lon, lat)
fAPAR_input <- as.data.frame(cbind(lonlat,final_fAPAR))
names(fAPAR_input) <- c("lon","lat","fAPAR")
summary(fAPAR_input)

#here we merge fAPAR with age and continent data.
continent_age_fAPAR <- merge(continent_age, fAPAR_input, by=c("lon","lat"), all.x = T, sort=F )
summary(continent_age_fAPAR)
dim(continent_age_fAPAR)

#when fAPAR = NA, then those grid's age also = NA. After this, age = 0 only had one possibility, that is, missing data. We will subset them later on and replace them to mean value of local continent.
for (i in 1:nrow(continent_age_fAPAR)){
  if (is.na(continent_age_fAPAR$fAPAR[i]) == TRUE){
    continent_age_fAPAR$new_age[i]<- NA} else { 
      continent_age_fAPAR$new_age[i]<- continent_age_fAPAR$age[i]} 
}

continent_age_fAPAR2 <- continent_age_fAPAR[,c("lon","lat","new_age")]

coordinates(continent_age_fAPAR2) <- ~lon+lat 
gridded(continent_age_fAPAR2) <- TRUE
r <- raster(continent_age_fAPAR2, "new_age") 
plot(r) #we will start working from this map! Because it actually clarfies which grid stand-age = NA (in white), which grid stand-age has missed data (which temporaily considered = 0, and shown in grey, will be interpolated soon) .


#4. Now, start interpolating each continent's missing data (when age = 0) as mean value of local continent
age_final <- as.data.frame(continent_age_fAPAR[,c("lon","lat","area","new_age")])

mylist <- vector(mode = "list", length =25) # for specifying gridded data at certain degrees

for (i in c(1:8,10:24)){ # area 9 and 25 did not have such problem (missing data of stand-age; i.e. age = 0)
  empty_age <- subset(age_final, (area == i & new_age == 0)) #find missing grids (new_age ==0, classfied as missing data)
  available_age <- subset(age_final, (area == i & new_age > 0)) #find non-missing grids and calculate mean
  empty_age$final_age <- mean(available_age$new_age)
  mylist[[i]] <- empty_age
  #print(i)
}

all_age <- as.data.frame(do.call(rbind, mylist))
dim(all_age)

#South AUS (area = 26), however, was interpolated by area =25 's mean stand-age value

South_AUS_empty_age <- subset(age_final, (area == 26 & new_age == 0) )
North_AUS_available_age <- subset(age_final, (area == 25 & new_age > 0))
South_AUS_empty_age$final_age <- mean(North_AUS_available_age$new_age)

all_age2 <- rbind(all_age,South_AUS_empty_age)

all_age3 <- all_age2[,c("lon","lat","final_age")]

#5. merge new interpolated subset of age dataframe into last complete dataframe, and generating findal data to be used.
final <- merge(continent_age_fAPAR, all_age3, by=c("lon","lat"), all.x = T,sort = T)

for (i in 1:nrow(final)){
  if (is.na(final$final_age[i]) == TRUE){
    final$age_used[i] <- final$new_age[i]} else {
      final$age_used[i] <- final$final_age[i]} 
}

final2 <- final[,c("lon","lat","age_used")]
names(final2) <- c("lon","lat","age")

final_data <- final2

coordinates(final2) <- ~lon+lat 
gridded(final2) <- TRUE
r <- raster(final2, "age") 
#here is our final map!
plot(r) 

#6. convert dataframe to nc file as input in nimpl project
summary(final_data)
outlier <- (subset(final_data,age ==0))
dim(outlier)
#map("world", fill=TRUE, col="white", bg="white", ylim=c(-90, 90),xlim = c(-180,180), mar=c(1,0,0,1))
#points(outlier$lon,outlier$lat, col="red", pch=16,cex=1.5)

# it seems to still show 407 grids = 0 (normally in edge or sea). They may not be covered by fAPAR and continent grids from previous analysis, let's just simply assume them as NA.

final_data$age[final_data$age == 0] <- NA

summary(final_data)
#now final_data is ready to be used, let's firstly change its lat, lon order correctly, then convert all NA to 9999

final_data2 <- final_data[order(final_data[,2],final_data[,1]),]

df_age <- final_data2

#output age map
coordinates(final_data2) <- ~lon+lat 
gridded(final_data2) <- TRUE
rage <- raster(final_data2, "age") 
plot(rage)

#output nc file - In Euler its path is same: "~/data/nimpl_sofun_inputs/map/Final_ncfile"
summary(df_age)
age_nc <- list(df_to_grid(df_age,varnam = "age", lonnam = "lon", latnam = "lat"))
names(age_nc) <- "age"
varams = "age"
test <- list(lon,lat,age_nc,varams)
names(test) <- c("lon","lat","vars","varams")
write_nc2(test,varnams = "age",long_name = "stand age",units = "years",
          path = "~/data/nimpl_sofun_inputs/map/Final_ncfile/age.nc")
``` 

#2. fAPAR
```{r}
library(raster)
library(ncdf4)
library(dplyr)
library(maps)
library(rgdal)

ncfname <- paste ("~/data/fAPAR/fAPAR3g_v2/", "fAPAR3g_v2_1982_2016_FILLED", ".nc", sep="")

#ncfname <- paste ("E:/C-N cycling/Carbon allocation/fAPAR/fAPAR HUANYUAN/", "fAPAR3g_v2_1982_2016_FILLED", ".nc", sep="")
dname <- "FAPAR_FILLED"

ncin <- nc_open(ncfname)

lon <- ncvar_get(ncin,"LON")
nlon <- dim(lon) 

lat<-ncvar_get(ncin,"LAT")
nlat <- dim(lat)

FAPAR <- ncvar_get(ncin,"FAPAR_FILLED")
nc_close(ncin)

pre.vec.long <- as.vector(FAPAR)

pre.mat <- matrix(pre.vec.long, nrow = nlon * nlat, ncol = 420) # 259200 * 420 (420 is 35 years: 1982-2016)

fAPAR1982_2011 <- pre.mat[,c(1:360)] #extrat fAPAR from 1982-2011

final_fAPAR <- rowMeans(fAPAR1982_2011,na.rm = TRUE)

lonlat <- expand.grid(lon, lat)
fAPAR_input <- as.data.frame(cbind(lonlat,final_fAPAR))
names(fAPAR_input) <- c("lon","lat","fAPAR")

df_fAPAR <- fAPAR_input

coordinates(fAPAR_input) <- ~lon+lat 
gridded(fAPAR_input) <- TRUE
r3 <- raster(fAPAR_input, "fAPAR") 
plot(r3)

#output nc file - In Euler its path is same: "~/data/nimpl_sofun_inputs/map/Final_ncfile"
df_fAPAR$fAPAR[df_fAPAR$fAPAR == "NaN"] <- NA
summary(df_fAPAR)

fAPAR_nc <- list(df_to_grid(df_fAPAR,varnam = "fAPAR", lonnam = "lon", latnam = "lat"))
names(fAPAR_nc) <- "fAPAR"
varams = "fAPAR"
test <- list(lon,lat,fAPAR_nc,varams)
names(test) <- c("lon","lat","vars","varams")
write_nc2(test,varnams = "fAPAR",long_name = "fAPAR",units = "unitless",
          path = "~/data/nimpl_sofun_inputs/map/Final_ncfile/fAPAR.nc")
```

